### ISSUE TITLE
Usage in auto scaling

### ISSUE THREAD

**Issue by sly-roar** [mogadanez/sqsd#11]
Hi,

Thanks for the project. It is very useful in time of building applications via microservices and using Docker.

But we tried to use SQSd in an application with an enabled auto scaling and encountered an issue when one SQS message is processed by two workers simultaneously. 

Could you tell me, product has an ability to work in environments that scale automatically?
If yes, is there a setting of how a correct behavior, like one message is processed by one worker, could be set?

Thanks in advance.

**Comment by jpassaro** [comment]
Google search for "sqs message processed twice" produced the following link:

> https://stackoverflow.com/questions/23260024/how-to-prevent-duplicate-sqs-messages

The very detailed answer there suggests that this is simply something your application needs to be able to handle. The duplicate message appears to be something that just happens now and then. It's not the fault of the consumer (i.e. `sqsd`), it's intrinsic to SQS and probably to many queuing solutions.
