### ISSUE TITLE
Cron support

### ISSUE THREAD

**Issue by jpassaro** [mogadanez/sqsd#6]
Amazon's sqsd supports scheduled jobs via a `cron.yaml` spec file. It looks like this would be pretty easy to support since there are at least a couple of npm packages supporting scheduling jobs according to a cron schedule.

Have the developers considered such a feature? Just wanted to check before I possibly started working on adding it.

**Comment by mogadanez** [comment]
This package designed to  receive  messages from queue and forward it to workers, 
Probably you  want make  some simple independent project which put  messages to queue by schedule

**Comment by jpassaro** [comment]
My understanding was the package was designed to emulate the Amazon SQSD daemon, whose functionality is mostly as you describe but also [supports `cron.yaml`](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html#worker-periodictasks). Hence my thinking that it might be worth supporting not just in a separate project but in this one, for a fuller AWS SQSD emulator.

But you've basically answered my question -- sounds like it's not on your radar. I may try implementing in a fork. You may see a PR at some point.

Thank you!
